### ISSUE TITLE
您好！请问您在链路预测的时候是如何对有向图进行链路预测的呢？

### ISSUE THREAD

**Issue by F-windyy** [flyingtango/DiGCN#4]
研一小菜鸡被老板要求做有向图的链路预测，像GAE那样两个节点的嵌入做内积的话还原的是无向图，没什么思路很苦恼，正好看见了您的文章，所以就想问一下您是怎么处理有向图的链路预测的？

**Comment by flyingtango** [comment]
链路预测是指有向图的link prediction吗？GAE具体是哪篇文章呢？

**Comment by F-windyy** [comment]
嗯嗯，对的老哥，就是有向图的link prediction，GAE是Kipf的Variational Graph Auto-Encoders，我看您的代码中只有node classification的任务，所以不知道您的有向图link prediction是怎么做的

**Comment by flyingtango** [comment]
你可以看一下这篇文章[MagNet](https://arxiv.org/pdf/2102.11391.pdf)和他们的[implementation](https://github.com/matthew-hirn/magnet)，有我的方法DGCN, DiGCN和他们方法MagNet的实现。

**Comment by F-windyy** [comment]
好的 非常感谢
