### ISSUE TITLE
Question about equation 4

### ISSUE THREAD

**Issue by JhuoW** [flyingtango/DiGCN#5]
Dear author,
I'm a little confused about Eq.4. You adopt symmetric normalized directed Laplacian proposed by Chung F (2005), however, It is not clear to me why the graph filter in Eq 4 can reflect directed property?  Since it is a symmetric matrix.

**Comment by flyingtango** [comment]
Hi,

Thank you for your interest in our work. We consider that the directed graph Laplacian proposed by Chung has already encodes directed information, such as this form satisfying Cheeger inequality. Although the final form is symmetric, the eigenvector matrix for performing normilizaton varies with the directed graph structure.

Regards,
Zekun

**Comment by JhuoW** [comment]
Thanks for your explanation.
